source 'https://rubygems.org'

gem 'sinatra'
gem 'rspec'
gem 'haml'
gem 'pg'
gem 'activerecord'
gem 'arel'
gem 'squeel'
gem 'debugger'
gem 'mail'
gem 'thin'
gem 'json'
gem 'active_model_serializers'
gem 'sinatra-contrib'
gem 'sass'
gem 'annotate'
gem 'foreman'
gem "resque", "~> 2.0.0.pre.1", github: "resque/resque"

